{{- if .Values.vault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "hermes.fullname" . }}-vault
spec:
  provider: vault
  parameters:
    roleName: {{ .Values.vault.roleName | quote }}
    vaultAddress: {{ .Values.vault.address | quote }}
    objects: |
      - objectName: hotkey
        secretPath: {{ .Values.vault.secretPath }}
        secretKey: {{ .Values.vault.secretField }}
{{- end }}
