apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes.fullname" . }}-validator
  labels:
    app.kubernetes.io/name: {{ include "hermes.name" . }}
    app.kubernetes.io/component: validator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "hermes.name" . }}
    app.kubernetes.io/component: validator
  ports:
    - name: subtensor
      port: 9944
      targetPort: subtensor
